[package]
name = "rust-gb"
version = "0.1.0"
authors = ["Guy Dunton PC <guy.dunton@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.105.0"
rand = "0.6.0"
image = "0.22.3"
lazy_static = "1.4.0"
rust-catch = { git = "https://github.com/gdunton/rust-catch", rev = "HEAD" }

[profile.release]
debug = true
